### ISSUE TITLE
W100 warning if there are spaces/newlines in the \ProvidesExplPackage or \ProvidesExplFile declaration

### ISSUE THREAD

**Issue by u-fischer** [Witiko/expltools#7]
This works:

~~~~
\ProvidesExplFile{example.tex}{2024-04-09}{1.0.0}{An example file}
~~~~

But e.g.

~~~~
\ProvidesExplFile {example.tex} {2024-04-09} {1.0.0} {An example file}
~~~~

or

~~~~
\ProvidesExplPackage {tagpdf} {2024-12-04} {0.99k}
  { LaTeX kernel code for PDF tagging }
~~~~

gives

~~~~
tagpdf.sty:                                           W100 no standard delimiters
~~~~

**Comment by Witiko** [comment]
It was my recollection as an expl3 user that `\ProvidesExplPackage` was essentially `\def` with `#1#2#3#4`, i.e. no spaces allowed. However, if a less restricted syntax is permitted, we can and should allow for that. Sadly, `interface3.pdf` is quite scant on details about what's the actual syntax and when exactly the expl3 catcodes are enabled (before/after the arguments? The current code assumes after.):

![image](https://github.com/user-attachments/assets/e0798f91-43f0-4d9a-b7bb-73c37bc8875b)

However, I can read the l3kernel code to some extent and look into what's actually legal.

**Comment by josephwright** [comment]
> It was my recollection as an expl3 user that `\ProvidesExplPackage` was essentially `\def` with `#1#2#3#4`, i.e. no spaces allowed.

Yes to the first part, but with undelimited arguments, TeX looks for _balanced text_ so the spaces are ignored.

**Comment by u-fischer** [comment]
> It was my recollection as an expl3 user that `\ProvidesExplPackage` was essentially `\def` with `#1#2#3#4`, i.e. no spaces allowed.

That's not expl3 but TeX:

~~~~
\documentclass{article}
\def\blub#1#2{-#1-#2-}
\begin{document}

\blub {abc} {cde}

\end{document}
~~~~

**Comment by Witiko** [comment]
I might actually learn something new about TeX from this project!
