### ISSUE TITLE
Error "module 'explcheck-cli' not found"

### ISSUE THREAD

**Issue by muzimuzhi** [Witiko/expltools#9]
After running `(sudo) tlmgr install expltools` (on macOS), `explcheck` is available as a CLI program, but executing `explcheck` gives
```
$ explcheck
/Library/TeX/texbin/explcheck:3: module 'explcheck-cli' not found:
	no field package.preload['explcheck-cli']
	no file '/usr/local/share/lua/5.3/explcheck-cli.lua'
	no file '/usr/local/share/lua/5.3/explcheck-cli/init.lua'
	no file '/usr/local/lib/lua/5.3/explcheck-cli.lua'
	no file '/usr/local/lib/lua/5.3/explcheck-cli/init.lua'
	no file './explcheck-cli.lua'
	no file './explcheck-cli/init.lua'
	no file '/usr/local/lib/lua/5.3/explcheck-cli.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './explcheck-cli.so'
```

It seems `require("explcheck-cli")` alone is not able to search for Lua modules located in `texmf-dist/scripts/expltools/`
https://github.com/Witiko/expltools/blob/d23f333a012b276fb0a1a3d44c14e9c91683a624/explcheck/src/explcheck.lua#L2-L3

Learnt from how `l3build` manages to [load `l3build-*.lua` modules from within `l3build.lua`](https://github.com/latex3/l3build/blob/f75745818250cc873638af4f7c2506c171a2cc41/l3build.lua#L45-L50), I find adding `kpse.set_program_name("kpsewhich")` is suffice to load `explcheck-cli` module.

Furthermore, `l3build` also restricts it to only load internal modules from the same path of `l3build.lua`, for perhaps better support for testing and debugging. The wrapper then becomes
```lua
#!/usr/bin/env texlua
-- This is test-explcheck.lua
local lookup           = kpse.lookup
local match            = string.match

kpse.set_program_name("kpsewhich")
local build_kpse_path = match(lookup("explcheck.lua"),"(.*[/])")
local function build_require(s)
  require(lookup("explcheck-"..s..".lua", { path = build_kpse_path } ) )
end

-- A command-line interface for the static analyzer explcheck.
build_require("cli")
```

```
$ texlua test-explcheck.lua
Usage: test-explcheck.lua [OPTIONS] FILENAMES

Run static analysis on expl3 files.

Options:
	--max-line-length=N	The maximum line length before the warning S103 (Line too long) is produced.
	--warnings-are-errors	Produce a non-zero exit code if any warnings are produced by the analysis.
```

**Comment by muzimuzhi** [comment]
> After running `(sudo) tlmgr install expltools` (on macOS), `explcheck` is available as a CLI program, but executing `explcheck` gives

Paths of related files
```
$ which explcheck
/Library/TeX/texbin/explcheck
$ ls -l $(which explcheck)
lrwxrwxrwx  1 root  wheel    48B Dec  6 05:41 /Library/TeX/texbin/explcheck -> ../../texmf-dist/scripts/expltools/explcheck.lua
$ kpsewhich explcheck.lua
/usr/local/texlive/2024basic/texmf-dist/scripts/expltools/explcheck.lua
$ kpsewhich explcheck-cli.lua
/usr/local/texlive/2024basic/texmf-dist/scripts/expltools/explcheck-cli.lua
```

Also `tlmgr info --list expltools` gives
```
...
run files:
  texmf-dist/scripts/expltools/explcheck-cli.lua
  texmf-dist/scripts/expltools/explcheck-format.lua
  texmf-dist/scripts/expltools/explcheck-issues.lua
  texmf-dist/scripts/expltools/explcheck-preprocessing.lua
  texmf-dist/scripts/expltools/explcheck.lua
...
bin files (all platforms):
 bin/universal-darwin/explcheck
```

**Comment by Witiko** [comment]
Thanks for the extensive write-up, I knew I was forgetting something!

> Furthermore, `l3build` also restricts it to only load internal modules from the same path of `l3build.lua`, for perhaps better support for testing and debugging.

I am not sure this is necessary, it seems OK if users override the standard files `explcheck-*.lua` with updated files in the current working directory. The filenames seem long enough that unintended naming collisions should not be an issue. Therefore, it seems sufficient to load and set up the library `kpse` in the wrapper script `explcheck.lua`.

**Comment by muzimuzhi** [comment]
> > Furthermore, `l3build` also restricts it to only load internal modules from the same path of `l3build.lua`, for perhaps better support for testing and debugging.
> 
> I am not sure this is necessary, ...

TBH I'm not sure its necessity too.

I traced down to the discussion when those lines were added to `l3build.lua` (https://github.com/latex3/l3build/commit/a88921c6dfebdc67ee8bbae3b5a09e07b8d0c71a), see https://github.com/latex3/l3build/issues/35#issuecomment-351323713 and https://github.com/latex3/l3build/issues/35#issuecomment-351353972.

Maybe @josephwright can recall some context.

**Comment by gucci-on-fleek** [comment]
See also [this thread](https://tug.org/pipermail/tex-live/2024-December/050968.html) on the TeX Live mailing list.

**Comment by josephwright** [comment]
When we split from one file, we wanted in `l3build` to be sure there was no possible confusion - you want exactly one known state of your Lua code (or at least we do).

**Comment by gucci-on-fleek** [comment]
@Witiko

> I am not sure this is necessary, it seems OK if users override the standard files `explcheck-*.lua` with updated files in the current working directory. The filenames seem long enough that unintended naming collisions should not be an issue. Therefore, it seems sufficient to load and set up the library `kpse` in the wrapper script `explcheck.lua`.

Unless you're planning on adding the `explcheck` to the restricted shell-escape list, then this strategy (just using a plain `require "explcheck-cli"`) seems fine to me; it'll certainly make it much easier for you to debug the tool.

---

@muzimuzhi
 
> ```lua
> #!/usr/bin/env texlua
> -- This is test-explcheck.lua
> local lookup           = kpse.lookup
> local match            = string.match
> 
> kpse.set_program_name("kpsewhich")
> local build_kpse_path = match(lookup("explcheck.lua"),"(.*[/])")
> local function build_require(s)
>   require(lookup("explcheck-"..s..".lua", { path = build_kpse_path } ) )
> end
> 
> -- A command-line interface for the static analyzer explcheck.
> build_require("cli")
> ```

Probably more robust and a little bit easier to set the path to `$TEXMFSCRIPTS` than to lookup `explcheck.lua` and try and extract its parent directory:

> 

```lua
    -- Find the script, searching **only** in the scripts directories.
    local path = kpse.lookup(
        name,
        { path = kpse.var_value("TEXMFSCRIPTS"), format = "lua" }
    )
```
([`extractbb-chooser.lua:55-59`](https://github.com/gucci-on-fleek/extractbb/blob/eb0f8d8bffe7d422288bd0c8fe80c544b3997e8e/source/extractbb-chooser.lua#L55-L59))

**Comment by Witiko** [comment]
> Unless you're planning on adding the `explcheck` to the restricted shell-escape list, then this strategy (just using a plain `require "explcheck-cli"`) seems fine to me; it'll certainly make it much easier for you to debug the tool.

Not really, it's a command-line tool.

> Probably more robust and a little bit easier to set the path to `$TEXMFSCRIPTS` than to lookup `explcheck.lua` and try and extract its parent directory: [...]

That's true for the current release but we should move all files `explcheck-*.lua` except `explcheck.lua` away from `scripts/expltools` to `tex/luatex/expltools`, since these are not executables but rather library modules that can be loaded independently. Providing a file .tds.zip with the next CTAN upload should do the trick.

**Comment by gucci-on-fleek** [comment]
@Witiko 

> However, we should perhaps move all files `explcheck-*.lua` (except `explcheck.lua`) from `scripts/expltools` to `tex/luatex/expltools`, since these are not executables but rather library modules that can be used independently. Providing a file .tds.zip with the next CTAN release and not leaving the placement up to distributors should do the trick.

Hmm, I'd actually argue that the correct place for Lua code that can be used from either `texlua` or `luatex` (or even just plain `lua`) is `scripts/<pkg>/`, and _not_ `tex/luatex/<pkg>/`. Looks like TeX Live has a mix of both right now:

#### `scripts/<pkg>/`

- `lua-physical`
- `lua-uca`

#### `tex/luatex/<pkg>/`

- `lua-uni-algos`
- `luaxml`
- `penlight`

I'll email Karl about this some time this weekend and I'll let you the response.

**Comment by josephwright** [comment]
> Hmm, I'd actually argue that the correct place for Lua code that can be used from either `texlua` or `luatex` (or even just plain `lua`) is `scripts/<pkg>/`, and _not_ `tex/luatex/<pkg>/`. Looks like TeX Live has a mix of both right now:
> #### `scripts/<pkg>/`
> 
>     * `lua-physical`
> 
>     * `lua-uca`

Agreed - might be worth talking with @zanguin too.

**Comment by Witiko** [comment]
> Hmm, I'd actually argue that the correct place for Lua code that can be used from either texlua or luatex (or even just plain lua) is scripts/<pkg>/, and not tex/luatex/<pkg>/.

However, `tds.pdf` says that `scripts` is "for platform-independent executables," which isn't right either, because not all .lua files are executables. Some are just code modules to be imported.

Perhaps there just isn't a good place fotlr these at the moment, and we may need a new top-level directory `lua` next to the top-level directory `tex`.

**Comment by gucci-on-fleek** [comment]
> However, `tds.pdf` says that `scripts` is "for platform-independent executables," which isn't right either, because not all .lua files are executables. Some are just code modules to be imported.

Well yes, but `tds.pdf` isn't really very accurate anymore. I once suggested to Karl that I put some files in `tex/generic/images/` and that was (sensibly) rejected. `tds.pdf` also strongly recommends/requires that “[file] extensions may not exceed three characters” and gives advice for how to deploy TDS on VMS.

But I still think that it _could_ be interpreted as saying that `scripts` is an appropriate location for these files:

> Truly auxiliary scripts which are invoked directly by other programs, rather than wrapper scripts, may also be placed here. That is, `scripts` also serves as a platform-independent analog of the standard Unix `libexec` directory.

---

> Perhaps there just isn't a good place for these in the TDS at the moment, and we may need a new top-level directory `lua` next to the top-level directory `tex`.

A definite +1 to that in principle, but I do wonder what that might break.

> Regardless, I am happy to keep using the directory `scripts` for the files `explcheck-*.lua` before things have cleared up.

Either location is probably fine, so you can put it wherever you want for the time being.

**Comment by kberry** [comment]
Don't take 'executables' in the TDS too seriously; we just didn't think about (have any) non-executable modules back then.  scripts/ is indeed rather like a platform-independent libexec. Legalistic reading of TDS is not useful.

Either tex/* or scripts/* is fine. LUAINPUTS reads both. In TL, I typically use whichever seems most natural for the package at hand, e.g., something that is mostly TeX but has a .lua helper I'll put in tex/, something that's mostly or entirely Lua I'll put in scripts/. I don't claim perfect consistency, and, as I say, it doesn't matter.

I don't see the benefit of adding a top-level lua/. It would just be Yet Another place to look for stuff, require changing all the Lua-related search paths, etc. Pretend that scripts/ is whatever you have in mind :).

**Comment by kberry** [comment]
Regarding naming: although I didn't make an issue out of it, what concerned me was "explcheck" being in a package named "expltools". In a way you are laying claim to the every expl*.lua name. However, I knew you would be reasonable with naming. As long  there's a reasonable chance that there will be a second script in expltools someday, which I gathered there is, it seemed ok to let this one be an exception to the usual rules.

**Comment by kberry** [comment]
FWIW, I rather agree with Vit in principle about letting users override the .lua files with their own if they wish to. That's one of the things that makes free software work.

BTW, Heiko made me add "subdir searching" to kpathsea -- not the standard recursive searching, but what's exposed in kpsewhich --subdir, specifying a string (directory) that the match must end with. I don't know how or if it ever got used or if it's exposed in the Lua API.

**Comment by Witiko** [comment]
> Regarding naming: although I didn't make an issue out of it, what concerned me was "explcheck" being in a package named "expltools". In a way you are laying claim to the every expl*.lua name. However, I knew you would be reasonable with naming. As long there's a reasonable chance that there will be a second script in expltools someday, which I gathered there is, it seemed ok to let this one be an exception to the usual rules.

@kberry: Thank you for your feedback and for raising this concern. I understand the importance of keeping naming conventions clean and ensuring no unnecessary claims over potential names. My intention with the expltools bundle is indeed to include multiple tools over time, not just explcheck. To that end, I explicitly registered the expltools prefix with the LaTeX team in https://github.com/latex3/latex3/pull/1556 to ensure that the prefix was not reserved for other purposes.

That said, I completely understand your perspective, and if you believe that renaming the bundle to "explcheck" (focusing on this specific tool for now) would be better for the long-term health and clarity of naming conventions, I am more than willing to make that adjustment. Please let me know what you think is best.

**Comment by kberry** [comment]
Thanks for understanding. I'm content to leave things as they are
(pkgname=expltools, filenames for first tool=explcheck*). With other
authors, I might not be so laissez-faire :).
